### ISSUE TITLE
confirm async 6.0.x baseline should be jdk 17

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-async#155]
https://github.com/grails/grails-async/commit/42ba9a336b13701d805b9e267ccc44dc63be5bed

**Comment by matrei** [comment]
If I recall correctly, Async 6.0.x was for Grails 7 and already existed (but was not the main branch) when @davydotcom started his work on a new 7.0.x branch.

So 6.0.x can be probably be discarded.

**Comment by codeconsole** [comment]
so should Grails 7 be using Async 6?  @jamesfredley why did we burn a major version?

**Comment by codeconsole** [comment]
perhaps we should just delete 6 and rename 7 to 6?

**Comment by codeconsole** [comment]
I vote branch -D 6.x and rename 7.x to 6.x

**Comment by matrei** [comment]
Yes, renaming 7.0.x to 6.0.x is probably not a bad idea. Any objections @davydotcom ?

**Comment by jamesfredley** [comment]
I don't know on 6.0.x vs 7.0.x branches.  I think merging 7.0.x into 6.0.x would be the better route and then removing 7.0.x.

**Comment by codeconsole** [comment]
@jamesfredley why is there anything in 6 that we need?

**Comment by jamesfredley** [comment]
https://github.com/grails/grails-async/compare/7.0.x...6.0.x

**Comment by jamesfredley** [comment]
github search is down, but we will have a few places to update from 7.0.0-SNAPSHOT To 6.0.0-SNAPSHOT

https://github.com/search?q=org%3Agrails+asyncVersion&type=code

**Comment by codeconsole** [comment]
Merged, 6.0.x is now default branch https://github.com/grails/grails-async
