### ISSUE TITLE
grails-async M1 references grails-core 7.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-async#172]
I believe you can't have any references to any SNAPSHOT versions in any pom and that is why I stressed releasing grails-core first to github.  While I haven't tested my theory, I am pretty sure that if you use, for instance, the M1 version of async, you will not be able to use the m1 version of grails core.  https://repo1.maven.org/maven2/org/grails/plugins/async/6.0.0-M1/async-6.0.0-M1.pom.  

This is because async depends on grails:grails-core:7.0.0-SNAPSHOT and 7.0.0-SNAPSHOT > 7.0.0-M1 so the snapshot will always resolve over the M1.  This means an M2 version of async will need to be released.

I release this was an oversight, but there should be no official announcement regarding Grails 7 M1 until every pom is verified to not have any SNAPSHOT references.  (Unless I am wrong about my suspicion of course).

This includes the grails asset pipeline plugin with points to the snapshot grails bom which will make everything resolve snapshots again https://repo1.maven.org/maven2/com/bertramlabs/plugins/asset-pipeline-grails/5.0.5/asset-pipeline-grails-5.0.5.pom (edited)

**Comment by jdaugherty** [comment]
This was fixed in M2
