### ISSUE TITLE
Upgrade to Groovy 3.0.7 and Grails 5.0.x, and lasted version of  rxjava1, rxjava2

### ISSUE THREAD

**Issue by rainboyan** [grails/grails-async#38]
I have time to take this task

**Comment by rainboyan** [comment]
Current progress:
https://github.com/rainboyan/grails-async/tree/5.0.x

**Comment by puneetbehl** [comment]
I would appreciate all the contributions. Please open a draft pull-request and assign it to me once it is ready for review. I will try my best to get this published soon.

**Comment by rainboyan** [comment]
@puneetbehl Can you check this PR again? Blocked by this issue.

https://github.com/grails/grails-common-build/pull/3

**Comment by puneetbehl** [comment]
@rainboyan This is change is merged now.

**Comment by billgonemad** [comment]
I am not seeing a new release yet for Groovy 3.0.7/Grails 5.  @puneetbehl  was this done?  Latest version I am finding is 4.0.0
