### ISSUE TITLE
Alternative EventBus implementations are not being found on the classpath

### ISSUE THREAD

**Issue by alvarosanchez** [grails/grails-async#8]
The SPI descriptor is incorrect, and thus, no matter what is in the classpath, you end up seeing:

```
No event bus implementations found on classpath, using synchronous implementation
```

A PR is coming to fix this issue.

**Comment by graemerocher** [comment]
As a workaround you can define the `grailsEventBus` bean manually in `resources.groovy`:

```groovy
grailsEventBus(RxEventBus)
```
